# Constants variables for MXBLAS project
PROJECT_NAME_FULL = "MXBLAS"
PROJECT_NAME_ABBR = "MXBLAS"
PROJECT_NAME_FULL_LOWER = "mxblas"
PROJECT_NAME_ABBR_LOWER = "mxblas"


# MXBLAS Environment variables
DEBUG_FLAG = "MXBLAS_JIT_DEBUG"
NVCC_COMPILER_FLAG = "MXBLAS_NVCC_COMPILER"
CACHE_DIR_FLAG = "MXBLAS_CACHE_DIR"
PTXAS_VERBOSE_FLAG = "MXBLAS_PTXAS_VERBOSE"
JIT_PRINT_NVCC_COMMAND_FLAG = "MXBLAS_JIT_PRINT_NVCC_COMMAND"
PRINT_AUTOTUNE_FLAG = "MXBLAS_PRINT_AUTO_TUNE"

BUILD_FAILURE_INFO_PATH= "MXBLAS_BUILD_FAILURE_INFO_PATH"

PRINT_MATCHING_FLAG = "MXBLAS_PRINT_MATCHING"
PRINT_CONDITIONS_FLAG = "MXBLAS_PRINT_CONDITIONS"


